# Medium Matters

*The tragic tyranny of typeset pdfs in a less paginated era.*

The pdf reigns supreme as the medium in which academic papers must be published and oppresses us all with an iron fist.
OK, maybe that's a bit much but I'm dead serious about the fact that the anachronistic favoring of form in a dead medium over function in a current one is causing us issues larger than they might at first appear.
The dead tree is no longer medium on which most of us read academic papers, the screen now rules in this domain.
Yet we still format papers to be nicely typeset and printed, we even still organize figures together into panels so that the publishers need not spend as much money on color printed pages. 
What's wrong this this you could reasonably say, what's the problem with having papers nicely typeset for printing?
Nothing *per se* it would be fine if we were still reading the paper versions but we are not we are reading them electronically and typeset for print is not the best way to present information for easy comprehension on a screen.

Case-in-point try and read a pdf of a paper on a phone with a screen no larger than about 5", torturous right?
Whilst the mismatch is less extreme on a nice big desktop monitor there are still non-optimal aspects of reading something meant for print on a monitor just a little less extreme than the phone case.

The problem I think is a combination two things, information non-locality and poorer spacial information mapping on screens vs paper.

What do I mean by information non-locality?
When the information needed to understand something is spread widely through the manuscript and you have to go to many different places to piece together all the bits of information you need to understand a thing.
For a concrete example let us take the what in my opinion are the worst offenders in this space, Multi-panel figures.

## We need to talk about Multi-panel figures

(Apologies if my personal loathing of multi-panel figure comes through overmuch in the style and tone here, I tried to exercise some restraint)

What information do you usually need to interpret a panel in a figure?

- The figure itself
- The figure legend
- The place in the text which references the figure
- more often than not at least one disambiguation of a novel acronym

Each of these 4 pieces of information can be located on different pages in a modern manuscript.
Yes the figure and it's legend are sometimes of different pages (I'm looking at you Cell WTF?).
To drive this point home you can be looking at a situation like this:
Figure 6i was discussed on page 4, printed on page 5 and the legend for which is, for some ungodly reason, printed on page 6!
Oh and also the title for the figure is not on the figure but in the legend and helpfully features (YATA) yet another terrible acronym that was defined once in the abstract on page 1.

I don't know about you but a mere mortal such as myself needs some working memory spare to think about the underlying concepts that a manuscript is trying to communicate to me, and I do not appreciate having to cache as many a 4 look-up tables in my head just to be able to effectively read a figure, let alone reason further about it! 

I content that this problem is worse when looking at electronic representations of formats meant to be printed, at least in part because it is easier to form a mental map of the relationships between these different parts of the manuscript when it is printed.
When you have a physical copy the parts have relationships to one another in 3D space that take less effort to construct a mental model of.
Also it's just easier to arrange the pages so can actually look at the different parts and the same time.
e-reader like formats also suffer from this issue as they don't have fixed pagination so the relationships between objects are harder to model still as they are not even in fixed relationship to one another in a virtual 2D space.

I hypothesize that breaking up figure panels placing information, such as titles and abbreviations unnecessarily relegated to figure legends in the figure itself and placing figures in line in the text as they occur would increase reading speed and comprehension, especially in electronic media. I term this information-non locality minimization.

Specific hypotheses I'd like to see tested:

1. Time taken to read a paper with multi-panel figures will be longer than time taken when information-non locality is minimised.
2. Reading comprehension tests will be worse for papers with multi-panel figures than when information-non locality is minimised.
3. Hypotheses 1 & 2 will be true of both electronic and physical media but the effect size will be larger for electronic media.
4. Bound copies of papers with multi-panel figures will provide less of an advantage over information-non locality minimised copies than loose leaf / unbound prints.
5. Effect size of the advantage information-non locality minimized versions have over multi-panel figure versions will be larger in people with dyslexia. (I'm dyslexic and it's been thought of as an issue related to working memory)

If anyone wants to do this research get in touch I might even be willing to contribute to funding it.

To sum up Multi-panel figures are an anachronistic concession to typesetting color prints to a compact format for printing and they have no place in modern electronic publishing. 
They ruin the flow of reading a paper.
They represents an unreasonable assault on the working memory resources of a reader who is trying to understand what is likely a complex topic and create undue cognitive load for readers who need their full mental faculties about them to graple with complex scientific ideas.

Additionally I think that they encourage bad graphical practices.
Panels are labeled not with meaningfully interpretable titles as both our schooling and basic common sense about presenting information dictates they should be but with alphabet soup. 
These are bad practices for which we take school children to task for in science classes but seem to have collectively forgotten in the peer reviewed literature.
Multi-panel figures should be used ONLY when it is actually useful for the understanding of the content for visuals to be placed together.
We don't need to optimize for printing in electronic formats we can have as many full size color figures as we need to optimally convey our point.
This would be an improvement even if we stick to a pdf as the primary end point paradigm which I will be making a case against later.

(Rant over `r emo::ji("wink")` )

We will now be asking, what can you get when you ditch the static pdf as the primary end point?

## Interactivity, Animation, & More {#interact}

There is some skepticism over the value of interactivity and especially animation in actually being effective at communicating usefully interpetable scientific information.
Just as there a many ways to produce terrible uninformative graphs there are many ways for interactivity and animation to be ineffectually employed but there are a number of areas in which they excel at effective communication in ways not easily captured in static plots.

To make the point about interactivity I will largely let this little widget from [canvasXpress](https://canvasxpress.org/) make my point for me.
Imagine ever plot in a scientific paper worked like the widget below.
No seriously make it full screen and play around with it a bit, right click in the plot and take a look at the options.
Look at the code I wrote to get this level of functionality, I've left it visible above the plot - yes that's it.

```{r}
library(canvasXpress)
# TODO: make a better example plot
canvasXpress::canvasXpress(mtcars)
```

I'm serious really play with it before you move on, have you tired double clicking, have you looked in configure?

This sort of capability is particularly valuable for looking at publications of exploratory analyses where the authors publishing the work 

Let's Consider some other uses of interactivity.
You know those 'representative images' people put in their papers when they do a bulk analysis of images what if the representative image was a widget that picked one at random from the appropriate group in the dataset deposited at the [Image Data Archive](https://idr.openmicroscopy.org/) and changed it periodically?
A norm like this might have a positive effect on the representativeness of those images don't you think?


### The utility of animation for representing uncertainty

<iframe width="848" height="477" src="https://www.youtube-nocookie.com/embed/SjYwhku2si0" title="YouTube video player" frameborder="0" allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Objections to dropping pdfs

"We can't get rid of pdfs we need a version of the paper that we can archive!" I hear you cry.
Yes, we do archival formats are important but
the archival format does not have to be prettily typeset to minimize the number of color prints
there are archival formats as good or better than pdfs



In [Section \@ref(computational-irreproducibility) Computational Irreproducibility](#computational-irreproducibility) & 
In [Section \@ref(key-technologies) Key Technologies](#key-technologies) I will be making the case that a form of plain text document should be the definitive reference version, key end point and primary authoring format.

The separation of semantic content from formatting information (css / html)
why plain text? parseability - interoperability with many downstream text processing tools small, version control, temporal stability of format, open
